# Generated by Django 5.0.2 on 2024-02-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
